### ISSUE TITLE
Bee sound effect

### ISSUE THREAD

**Issue by EmanuelG-Gaming** [TeamNeiaron/Ion#2]
The Caretaker shoots Flare-like bullets, however, it does a very long and distorted (bee) buzzing sound effect. You can maybe replace this with a shorter, more fitting sound effect.

Not very important.

**Comment by SMOLKEYS** [comment]
unbee the bee

**Comment by EmanuelG-Gaming** [comment]
when the unit doesn't make wasp sounds

**Comment by SMOLKEYS** [comment]
~~spare a star?~~

**Comment by EmanuelG-Gaming** [comment]
~~perhape~~
